
ALTER TABLE public.menu ALTER COLUMN category TYPE text USING category::text;
DELETE FROM public.menu;

INSERT INTO public.menu (name, price, category, is_signature, is_available) VALUES
('Bread Roll (2pcs)', 115, 'Snacks', false, true),
('French Fry', 120, 'Snacks', false, true),
('Chatpate Masala French Fry', 130, 'Snacks', false, true),
('Aloo Chaat', 100, 'Snacks', false, true),
('Veg Cutlet', 110, 'Snacks', false, true),
('Hara Bara Kabab', 130, 'Snacks', false, true),
('Butter Toast', 80, 'Snacks', false, true),
('Poori Bhaji', 110, 'Snacks', false, true),
('Plain Maggi', 50, 'Snacks', false, true),
('Plain Butter Maggi', 70, 'Snacks', false, true),
('Veg Maggi', 60, 'Snacks', false, true),
('Veg Butter Maggi', 80, 'Snacks', false, true),
('Cucumber Salad', 50, 'Salad', false, true),
('Onion Salad', 60, 'Salad', false, true),
('Green Salad', 70, 'Salad', false, true),
('Kachumber Salad', 80, 'Salad', false, true),
('Fruit Salad', 120, 'Salad', true, true),
('Plain Dahi', 50, 'Raita & Papad', false, true),
('Plain Raita', 70, 'Raita & Papad', false, true),
('Boondi Raita', 75, 'Raita & Papad', false, true),
('Mix Veg Raita', 85, 'Raita & Papad', false, true),
('Fruit Raita', 120, 'Raita & Papad', true, true),
('Roasted Papad', 25, 'Raita & Papad', false, true),
('Fried Papad', 30, 'Raita & Papad', false, true),
('Masala Papad', 50, 'Raita & Papad', false, true),
('Steam Rice', 85, 'Rice', false, true),
('Jeera Rice', 110, 'Rice', false, true),
('Handi Pulao', 120, 'Rice', false, true),
('Matar Pulao', 115, 'Rice', false, true),
('Veg Pulao', 120, 'Rice', false, true),
('Spcl Kashmiri Pulao', 140, 'Rice', true, true),
('Fried Rice', 110, 'Rice', false, true),
('Veg Biryani', 120, 'Rice', false, true),
('Spcl Hyderabadi Biryani', 150, 'Rice', true, true),
('Plain Roti', 10, 'Tandoori Breads', false, true),
('Butter Roti', 15, 'Tandoori Breads', false, true),
('Plain Naan', 35, 'Tandoori Breads', false, true),
('Butter Naan', 40, 'Tandoori Breads', false, true),
('Paneer Naan', 65, 'Tandoori Breads', false, true),
('Stuff Naan', 60, 'Tandoori Breads', false, true),
('Missi Plain Roti', 40, 'Tandoori Breads', false, true),
('Missi Butter Roti', 45, 'Tandoori Breads', false, true),
('Missi Onion Roti', 40, 'Tandoori Breads', false, true),
('Lachha Paratha', 45, 'Tandoori Breads', false, true),
('Aloo Paratha', 80, 'Tandoori Parathe', false, true),
('Gobhi Paratha', 85, 'Tandoori Parathe', false, true),
('Paneer Paratha', 120, 'Tandoori Parathe', false, true),
('Mix Paratha', 100, 'Tandoori Parathe', false, true),
('Green Matar Stuffed Paratha', 100, 'Tandoori Parathe', false, true),
('Pudina Paratha', 65, 'Tandoori Parathe', false, true),
('Plain Paratha', 50, 'Tandoori Parathe', false, true),
('Aloo Jeera', 110, 'A La Carte', false, true),
('Aloo Matar', 110, 'A La Carte', false, true),
('Aloo Tamatar', 110, 'A La Carte', false, true),
('Aloo Gobhi', 110, 'A La Carte', false, true),
('Gobhi Masala', 120, 'A La Carte', false, true),
('Kadhai Gobhi', 120, 'A La Carte', false, true),
('Dum Aloo', 120, 'A La Carte', false, true),
('Kashmiri Dum Aloo', 130, 'A La Carte', false, true),
('Kadhai Aloo', 120, 'A La Carte', false, true),
('Aloo Palak (Seasonal)', 120, 'A La Carte', false, true),
('Paneer Stuff Shimla Mirch', 135, 'A La Carte', false, true),
('Chana Masala', 120, 'A La Carte', false, true),
('Kadhai Sev Bhaji', 120, 'A La Carte', false, true),
('Mix Veg', 140, 'A La Carte', false, true),
('Dal Fry', 90, 'Dal', false, true),
('Dal Tadka', 110, 'Dal', false, true),
('Dal Handi', 130, 'Dal', false, true),
('Dal Makhani', 140, 'Dal', false, true),
('Dal Maharani', 170, 'Dal', false, true),
('Matar Mushroom', 190, 'Mushroom', false, true),
('Kadhai Mushroom', 200, 'Mushroom', false, true),
('Mushroom Butter Masala', 210, 'Mushroom', false, true),
('Mushroom Paneer Butter Masala', 210, 'Mushroom', false, true),
('Chilly Mushroom', 190, 'Mushroom', false, true),
('Gravy Chaap', 150, 'Chaap', false, true),
('Kadhai Chaap', 160, 'Chaap', false, true),
('Chilly Chaap', 170, 'Chaap', false, true),
('Malai Chaap', 170, 'Chaap', false, true),
('Shahi Paneer', 180, 'Paneer', false, true),
('Matar Paneer', 170, 'Paneer', false, true),
('Chhole Paneer', 150, 'Paneer', false, true),
('Khoya Paneer', 190, 'Paneer', false, true),
('Handi Paneer', 210, 'Paneer', false, true),
('Paneer Butter Masala', 190, 'Paneer', false, true),
('Paneer Tikka Masala (gravy)', 210, 'Paneer', false, true),
('Paneer Tikka Masala (tandoori)', 230, 'Paneer', false, true),
('Paneer Pasanda', 210, 'Paneer', false, true),
('Kadhai Paneer', 200, 'Paneer', false, true),
('Paneer Bhujhia', 200, 'Paneer', false, true),
('Palak Paneer (seasonal)', 170, 'Paneer', false, true),
('Malai Kofta', 210, 'Paneer', false, true),
('Shahi Kaju Curry', 280, 'Paneer', true, true),
('Methi Matar Malai', 250, 'Paneer', false, true),
('Idli Sambhar', 109, 'South Indian', false, true),
('Bada Sambhar', 109, 'South Indian', false, true),
('Fried Idli', 129, 'South Indian', false, true),
('Butter Plain Dosa', 99, 'South Indian', false, true),
('Butter Masala Dosa', 149, 'South Indian', false, true),
('Masala Dosa', 129, 'South Indian', false, true),
('Garlic Masala Dosa', 109, 'South Indian', false, true),
('Paneer Dosa', 179, 'South Indian', false, true),
('Cheese Dosa', 189, 'South Indian', false, true),
('Spring Dosa', 209, 'South Indian', false, true),
('Cheese Masala Dosa', 209, 'South Indian', false, true),
('Panner Tikka Dosa', 249, 'South Indian', false, true),
('Onion Masala Dosa', 149, 'South Indian', false, true),
('Onion Tomato Uttapam', 159, 'South Indian', false, true),
('Onion Delight Uttapam', 159, 'South Indian', false, true),
('Mix Veg Uttapam', 159, 'South Indian', false, true),
('Cheese Uttapam', 199, 'South Indian', false, true),
('Plain Vada (2pcs)', 110, 'South Indian', false, true),
('Sambhar Vada (2pcs)', 125, 'South Indian', false, true),
('Idle Sambhar (2pcs)', 100, 'South Indian', false, true),
('Veg Steam Momos (8pcs)', 110, 'Chinese & Italian', false, true),
('Veg Fry Momos (8pcs)', 115, 'Chinese & Italian', false, true),
('Veg Gravy Momos (8pcs)', 120, 'Chinese & Italian', false, true),
('Veg Roll', 110, 'Chinese & Italian', false, true),
('Veg Paneer Roll', 120, 'Chinese & Italian', false, true),
('Veg Noodles Roll', 115, 'Chinese & Italian', false, true),
('Veg Paneer Noodles Roll', 130, 'Chinese & Italian', false, true),
('Veg Spring Roll', 120, 'Chinese & Italian', false, true),
('Veg Chowmein', 140, 'Chinese & Italian', false, true),
('Veg Paneer Chowmein', 150, 'Chinese & Italian', false, true),
('Veg Hakka Noodles', 150, 'Chinese & Italian', false, true),
('Veg Hakka Paneer Noodles', 160, 'Chinese & Italian', false, true),
('Paneer Noodles', 180, 'Chinese & Italian', false, true),
('Mushroom Noodles', 170, 'Chinese & Italian', false, true),
('Spcl Noodles', 190, 'Chinese & Italian', true, true),
('Chilly Potato', 120, 'Chinese & Italian', false, true),
('Honey Chilly Potato', 135, 'Chinese & Italian', false, true),
('Veg Salt & Paper', 110, 'Chinese & Italian', false, true),
('Chilli Mushroom', 170, 'Chinese & Italian', false, true),
('Veg Sandwich', 80, 'Chinese & Italian', false, true),
('Cheese Sandwich', 100, 'Chinese & Italian', false, true),
('Paneer Sandwich', 115, 'Chinese & Italian', false, true),
('Veg Grill Sandwich', 110, 'Chinese & Italian', false, true),
('Paneer Grill Sandwich', 130, 'Chinese & Italian', false, true),
('Cheese Grill Sandwich', 130, 'Chinese & Italian', false, true),
('Red Sauce Pasta', 150, 'Chinese & Italian', false, true),
('White Sauce Pasta', 165, 'Chinese & Italian', false, true),
('Pink Sauce Pasta', 170, 'Chinese & Italian', false, true),
('Veg Manchurian (Dry)', 160, 'Chinese & Italian', false, true),
('Veg Manchurian (Gravy)', 180, 'Chinese & Italian', false, true),
('Gobhi Manchurian (Dry)', 180, 'Chinese & Italian', false, true),
('Gobhi Manchurian (Gravy)', 200, 'Chinese & Italian', false, true),
('Chilly Paneer (Gravy)', 210, 'Chinese & Italian', false, true),
('Tomato Soup', 80, 'Soup', false, true),
('Manchow Soup', 100, 'Soup', false, true),
('Hot & Sour Soup', 110, 'Soup', false, true),
('Sweet Corn Soup', 110, 'Soup', false, true),
('Lemon Coriander Soup', 105, 'Soup', false, true),
('Veg Soup', 125, 'Soup', false, true),
('Spcl Soup', 140, 'Soup', true, true),
('Black Currant Shake', 120, 'Shakes', false, true),
('Strawberry Shake', 120, 'Shakes', false, true),
('Pineapple Shake', 120, 'Shakes', false, true),
('ButterScotch Shake', 120, 'Shakes', false, true),
('Banana Shake', 120, 'Shakes', false, true),
('MilkRose Shake', 80, 'Shakes', false, true),
('Litchi Shake', 120, 'Shakes', false, true),
('Chocolate Shake', 150, 'Shakes', false, true),
('Badam Shake', 150, 'Shakes', false, true),
('Mango Shake', 120, 'Shakes', false, true),
('Onion Catxiam Pizza', 159, 'Pizza', false, true),
('Plain Cheez Pizza', 139, 'Pizza', false, true),
('Tamato Cheez Pizza', 159, 'Pizza', false, true),
('Farm House Pizza', 249, 'Pizza', false, true),
('Special Pizza', 299, 'Pizza', true, true),
('Onion Cheez Pizza', 149, 'Pizza', false, true),
('Aloo Peti Burger', 39, 'Burger', false, true),
('Cheez Burger', 59, 'Burger', false, true),
('Mix Veg Burger', 69, 'Burger', false, true),
('Special Burger', 99, 'Burger', true, true),
('Paneer Burger', 119, 'Burger', false, true),
('Sweet Lassi', 70, 'Beverages', false, true),
('Special Kullad Tea', 29, 'Beverages', false, true),
('Lemon Tea', 25, 'Beverages', false, true),
('Hot Coffee', 49, 'Beverages', false, true),
('Green Tea', 49, 'Beverages', false, true),
('Black Tea', 49, 'Beverages', false, true),
('Pav Bhaji', 99, 'Pav Bhaji', false, true),
('Cheeze Pav Bhaji', 129, 'Pav Bhaji', false, true),
('Chhole Bhature', 119, 'Chhole Bhature', false, true),
('Special Thali (Shai Paneer, Dal, Rice, Raita, Buttar Naan-1, Roti-2, Achar, Salad, 1 Sweet)', 280, 'Thali', true, true);

DO $$
DECLARE
  v_user_id uuid;
BEGIN
  SELECT id INTO v_user_id FROM auth.users WHERE email = 'anshumesh.saini@gmail.com';
  IF v_user_id IS NULL THEN
    v_user_id := gen_random_uuid();
    INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
    VALUES ('00000000-0000-0000-0000-000000000000', v_user_id, 'authenticated', 'authenticated', 'anshumesh.saini@gmail.com', crypt('ayush5521', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', false, '', '', '', '');
  ELSE
    UPDATE auth.users SET encrypted_password = crypt('ayush5521', gen_salt('bf')), email_confirmed_at = COALESCE(email_confirmed_at, now()) WHERE id = v_user_id;
  END IF;
  INSERT INTO public.user_roles (user_id, role) VALUES (v_user_id, 'owner'::app_role)
  ON CONFLICT (user_id, role) DO NOTHING;
END $$;
